### PR TITLE
Add gamepad icons

### PR DESCRIPTION
**Pull request by burningserenity**
Adds gamepad icons in 12 point font.
See [here](https://github.com/diasurgical/devilutionX/pull/5357)

### CODE REVIEW

**Comment by AJenbo** [comment]
Shouldn't there be a .bin file for this font file?

**Comment by burningserenity** [comment]
There is but I don't see any other .bin files in this repo, so thought it wasn't appropriate to push that here. Same directory as the pcx?

**Comment by StephenCWills** [comment]
The pcx is used to generate clx, whereas the bin file would just be a straight copy if it was included in both repos.

**Comment by AJenbo** [comment]
We should probably look in to building the bin file in to the .clx so it isn't needed.

**Review by AJenbo — COMMENTED** [review]
We should credit the original artist of the symbols, same as with other fonts.

**Comment by StephenCWills** [comment]
@burningserenity Sorry if it wasn't clear. You don't need to include the bin file here, but we might move it here in the future.

**Review by StephenCWills — APPROVED** [review]

**Pull request merged**
