### PR TITLE
bundled-assets/fonts: Add text widths files

### PR DESCRIPTION
**Pull request by glebm**
Converts the `.bin` files from bundled assets (in the devilutionX repo)
to `.txt` file here with the following Ruby script:

```ruby
ARGV.each do |path|
  File.open(File.basename(path, '.bin') + '.txt', 'w') do |out|
    File.read(path, binmode: true).each_byte do |byte|
      out.puts byte
    end
  end
end
```

Also generates width `txt` files for `assets/fonts/` with the following Ruby script:

```ruby
FONT_SIZES = [ 12, 24, 30, 42, 46, 22 ]
CJK_WIDTHS = [ 17, 24, 28, 41, 47, 16 ]
CJK_RANGE = (0x30..0x9f)
HANGUL_WIDTHS = [ 15, 20, 24, 35, 39, 15 ]
HANGUL_RANGE = (0xac..0xd7)

ARGV.each do |path|
  size, row = File.basename(path, '.pcx').split('-')
  row_num = row.to_i(16)
  size_index = FONT_SIZES.index(size.to_i)
  width = if HANGUL_RANGE.include?(row_num)
            HANGUL_WIDTHS[size_index]
          elsif CJK_RANGE.include?(row_num) || row_num == 0xff
            CJK_WIDTHS[size_index]
          else
            fail "bad row 0x#{row} for size #{size}"
          end
  txt_path = File.join(File.dirname(path), "#{size}-#{row}.txt")
  File.write(txt_path, "#{width}\n")

  pcx = File.read(path, binmode: true).bytes
  pcx_width = (pcx[9] >> 2) + pcx[8] + 1
  File.delete(txt_path) if width == pcx_width
end
```

Refs https://github.com/diasurgical/devilutionX/issues/6361

### CODE REVIEW

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
i might not have created one for the ones where they match the image

**Comment by glebm** [comment]
> i might not have created one for the ones where they match the image

For these files it previously used the Japanese widths, which was a bug (e.g. uncropped size 22 has width 17px but we used 16px for it, resulting in 1px missing, hard to notice for emoji).
Now we actually use the image width. Row 0xff is a special case -- it should indeed use the Japanese widths so we add a widths file for it.

**Comment by glebm** [comment]
Force pushed with width txt files for CJK fonts, PTAL.

**Review by AJenbo — APPROVED** [review]

**Comment by AJenbo** [comment]
you can just merge when you think it's the correct time to do so :)

**Comment by glebm** [comment]
It's good to go but let's wait for 1.5.1 release, in case we need any other changes in this repo before then

**Comment by AJenbo** [comment]
v4 having VERSION 1 feels a bit odd

**Comment by glebm** [comment]
It's the VERSION 1 of that file since explicit versioning was introduced :)

**Comment by AJenbo** [comment]
I realize that at the current time, but I'm wondering about people of the future :)

**Comment by glebm** [comment]
Basically the version is separate from the devilutionx-assets release number because we won't necessarily change fonts.mpq on every devilutionx-assets release. I can change it to 4 if you prefer but they'll likely go out of sync anyway

**Review by AJenbo — APPROVED** [review]

**Pull request merged**
